import type {
  ArticleInfoType,
  BankItemType,
  MediaQueryInfo,
  TeamInfo,
  UserDetail,
  UserInfo
} from '@/interface/common'
import { isNative } from '@/utils/common'

export const defaultMediaQueryInfo: MediaQueryInfo = {
  height: 815,
  width: 375,
  top: isNative() ? 46 : 0,
  bottom: 0
}

export const defaultUserInfo: UserInfo = {
  money: '',
  frozen_money: '',
  total_money: 0,
  income_money: '',
  invest_not_finish: '',
  invest_not_earn: '',
  yuebao_earn: '',
  username: '',
  nickname: '',
  avatar: '',
  phone: '',
  phone2: '',
  sfz_name: '',
  sfz_number: '',
  level: 0,
  level_name: '',
  signin_num: 0,
  user_points: 0,
  invite: '',
  level_team: 0,
  level_team_name: '',
  level_extra: '',
  level_signin_amount: 0,
  outside_money: '',
  outside_frozen_money: '',
  outside_level_name: '',
  outside_level_img: '',
  outside_level_start_time: '',
  outside_level_end_time: '',
  outside_level_sign_amount: 0,
  rate: '',
  raffle_num: 0
}

export const defaultUserDetail: UserDetail = {
  uid: 0,
  shares_money: '',
  yuebao_money: '',
  yuebao_earn: '',
  yuebao_time: 0,
  yuebao_num: 0,
  recharge_money: '',
  recharge_num: 0,
  withdraw_money: '',
  withdraw_num: 0,
  signin_money: '',
  signin_num: 0,
  raffle_money: '',
  raffle_num: 0,
  team_invite: '',
  team_item: '',
  team_item_v1: '',
  team_item_v2: '',
  team_item_v3: '',
  team_invite_v1: '',
  team_invite_v2: '',
  team_invite_v3: '',
  team_invite_num: 0,
  team_invite_user: 0,
  team_recharge: '',
  team_recharge_v1: '',
  team_recharge_v2: '',
  team_recharge_v3: '',
  income_money: '',
  invest_money: '',
  invest_not_finish: '',
  invest_not_earn: '',
  invest_num: 0,
  user_points: 0,
  user_coupon: 0,
  bonus_num: 0,
  bonus_money: '',
  create_time: 0,
  update_time: 0,
  create_at: '',
  update_at: '',
  outside_recharge_money: '',
  outside_recharge_num: 0,
  outside_signin_num: 0,
  outside_signin_money: '',
  new_user_draw: 0,
  lv1Data: {} as any,
  lv2Data: {} as any,
  team_num: 0,
  team_recharge_money: '',
  team_withdraw_money: '',
  valid_recharge_num: 0
}

export const defaultTeamInfo: TeamInfo = {
  v0: 0,
  v1: 0,
  total_recharge: 0,
  total_withdraw: 0,
  total_invest: 0,
  today_recharge: 0,
  month_recharge: 0,
  total_earn: 0
}

export const defaultBankItem: BankItemType = {
  id: 0,
  uid: 0,
  username: '',
  phone: '',
  is_test: 0,
  type: 0,
  default: 0,
  name: '',
  bank_name: '',
  bank_branch: '',
  bank_account: '',
  coin_name: '',
  coin_blockchain: '',
  coin_account: '',
  alipay_account: '',
  alipay_img: '',
  wx_img: '',
  create_time: 0,
  update_time: 0,
  create_at: '',
  update_at: ''
}

export const defaultArticleInfo: ArticleInfoType = {
  id: 0,
  title: '',
  img: '',
  code: '',
  desc: '',
  release_time: 0,
  content: '',
  create_time: 0,
  update_time: 0,
  create_at: '',
  update_at: '',
  class_id: 0,
  class_name: ''
}
